### ISSUE TITLE
`ds_score_hhh4()` after `aggregate_moments()`

### ISSUE THREAD

**Issue by bastistician** [jbracher/hhh4addon#1]
I tried to continue the `example(ds_score_hhh4)` as follows:

```r
pred_aggr <- aggregate_moments(pred_salmonella,
    matrix(1, 1, 52, dimnames = list("observed1",NULL)))
ds_score_hhh4(pred_aggr)
```

This results in:
```
Error in t(pred$realizations - pred$mu_vector) %*% solve(pred$Sigma) : 
  non-conformable arguments
```
It seems that the aggregated predictions in `pred_aggr` no longer have an element `"mu_vector"`, but only `"mu"`. However, the value of the latter seems to be what is actually required to compute `ds_score_hhh4()` in this case.

A possible workaround seems to be:
```
pred_aggr$mu_vector <- pred_aggr$mu
```
(which then gives a scaled DSS of about 3.51 in the example.)

I am not sure if this workaround is valid in all settings, though.

**Comment by jbracher** [comment]
This was a problem in the naming of the return object of  `aggregate_moments`. Thanks for pointing this out, it should work now.

**Comment by bastistician** [comment]
Great, thanks!
