### ISSUE TITLE
plotHHH4lag_maps is exported but is not defined

### ISSUE THREAD

**Issue by barryrowlingson** [jbracher/hhh4addon#5]
Installing from latest github master results in an error:

```
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘hhh4addon’ in namespaceExport(ns, exports):
 undefined exports: plotHHH4lag_maps
Error: loading failed
```

`plotHHH4lag_maps` is in the `NAMESPACE` exports but I can't find a definition for it in the code. Its called once in `hhh4lag_plot.R`.

**Comment by jbracher** [comment]
Hi Barry, sorry for the belated reply. I somehow overlooked this issue during the holiday season. But I think it has been fixed for a while as somebody else alerted me of the same problem by email. If this is still of interest to you please let me know if everything works for you.
